### ISSUE TITLE
Keyboard problems 

### ISSUE THREAD

**Issue by exzos28** [zoontek/react-native-bars#15]
### Bug summary

windowSoftInputMode="adjustResize" not working after connecting react-native-bars
Keyboard always opens on top of the screen

The default state of the example from the repository:

https://user-images.githubusercontent.com/39951413/191948054-ca4898fe-7a67-4183-9096-842064f363b5.mov

After removing this line `RNBars.init(this, "dark-content");`
`android/app/src/main/java/com/rnbootsplashexample/MainActivity.java:26`

https://user-images.githubusercontent.com/39951413/191948078-de28b720-6c7f-48cc-ab04-3f4346ae9912.mov

In both cases I have `android:windowSoftInputMode="adjustResize"` in AndroidManifest.
And I expect the first case to have the same behavior. But it's not.

### Library version

1.2.2

### Environment info

```shell
"react-native": "0.70.0",
"react-native-bars": "^1.2.2",
"react-native-bootsplash": "^4.3.2",
```

### Steps to reproduce

This is an example with react-native-bootsplash template

### Reproducible sample code

```js
import * as React from "react";
import {
  ScrollView,
  TextInput,
  View,
} from "react-native";
import * as BootSplash from "react-native-bootsplash";

export const App = () => {
  React.useEffect(() => {
    BootSplash.hide();
  }, []);

  return (
    <ScrollView>
      <View style={{height: 500, borderWidth: 1, marginBottom: 10}} />
      <TextInput style={{borderWidth: 1, borderRadius: 10, padding: 10}} />
    </ScrollView>
  );
};
```

**Comment by zoontek** [comment]
@exzos28 I dug a bit on this.

- `mikepenz/MaterialDrawer` used [KeyboardUtil.java](https://github.com/mikepenz/MaterialDrawer/blob/v6.1.3/library/src/main/java/com/mikepenz/materialdrawer/util/KeyboardUtil.java)
- The same "fix" is available on [Google issue tracker](https://issuetracker.google.com/issues/36911528)
- In [React Native issues](https://github.com/facebook/react-native/issues/13000#issuecomment-397335819)
- And in [this gist](https://gist.github.com/grennis/2e3cd5f7a9238c59861015ce0a7c5584)

But as you can see in the comments, this is not ideal since it creates a flickering.

Dont' mind the navigation bar here, just focus on the status bar:

https://user-images.githubusercontent.com/1902323/192281350-14336428-30c3-4e9e-8982-616e28f86948.mp4

The "best" option for me seems to switch `windowSoftInputMode="adjustResize"` to `windowSoftInputMode="adjustPan"`:

https://user-images.githubusercontent.com/1902323/192281525-1daf02ed-d5a8-400b-b28b-eb290d1656b8.mp4

I will update the README accordingly.

**Comment by zoontek** [comment]
I published a new version with the README update: https://github.com/zoontek/react-native-bars/releases/tag/1.2.3

**Comment by exzos28** [comment]
Yes, but in this case, the page is panned, and the header moves up. This is undesirable in 99% of cases, in my opinion.
https://user-images.githubusercontent.com/39951413/192526854-77a490d9-5e38-40c1-9182-5fb96b2eedb9.mov

**Comment by zoontek** [comment]
@exzos28 I agree, but checked current solutions, and there's none viable.
Google does not seems to care about its OS.

**Comment by exzos28** [comment]
@zoontek I think we need to implement an api in your library to be able to turn transparent status and navigation bars on and off. It would be great.

**Comment by zoontek** [comment]
@exzos28 Sure, your company can hire me as a freelancer to take time to add this 🙂

**Comment by exzos28** [comment]
@zoontek 
I understand 🙂 I'll try to find some time and send MR. Does that make sense?

**Comment by zoontek** [comment]
I'm onto something: https://github.com/zoontek/react-native-bars/pull/16
Unfortunately, an issue seems to exists with `react-native-safe-area-context`.

Using React Native built-in `SafeAreaView`:

https://user-images.githubusercontent.com/1902323/192560319-f667562e-ca56-4bec-a91e-674715ac5328.mp4

Using `react-native-safe-area-context` one:

https://user-images.githubusercontent.com/1902323/192560395-bf2c9e9a-0b7f-4693-a00f-4d2b284b4b53.mp4

I will reach them soon to see what can cause this.
